import PDFKit
import XCTest
@testable import OpenGlasses

/// Plan HQ P1 item 2 — a clinical export says who wrote its text, in every format and on the
/// network POST alike: the recorder's speech-to-text, or a model. The caller decides; the service
/// states it. Provenance never carries the clinical text, and never the model's instructions.
@MainActor
final class MedicalExportProvenanceTests: XCTestCase {

    private static let promptCanary = "CANARY-PROMPT-BODY-7c2a19"
    /// Stands in for clinical content. It belongs in the document body and nowhere else.
    private static let clinicalCanary = "CANARY-CLINICAL-TEXT-e40b55"
    private static let transcript = "Patient reports \(clinicalCanary) since Tuesday."

    private var root: URL!
    private var suiteName = ""
    private var defaults: UserDefaults!
    private var store: FHIRConfigurationStore!
    private var service: MedicalExportService!

    override func setUp() {
        super.setUp()
        root = FileManager.default.temporaryDirectory
            .appendingPathComponent("MedicalExportProvenanceTests_\(UUID().uuidString)")
        suiteName = "MedicalExportProvenanceTests.\(UUID().uuidString)"
        defaults = UserDefaults(suiteName: suiteName)
        let secrets = InMemoryFHIRSecretStore()
        store = FHIRConfigurationStore(defaults: defaults, credentials: secrets, contexts: secrets)
        service = MedicalExportService(
            configurationStore: store,
            leases: MedicalExportLeaseCoordinator(store: MedicalExportFileStore(root: root)))
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: root)
        defaults.removePersistentDomain(forName: suiteName)
        super.tearDown()
    }

    private static func provenance() -> AIProvenance {
        AIProvenance.forAssessment(modelIdentifier: "test-model-1", providerClass: .cloud,
                                   promptSources: ["Instructions \(promptCanary)"],
                                   generatedAt: Date(timeIntervalSince1970: 1_700_000_000),
                                   appVersion: "2026.9 (400)")
    }

    private static let origins: [MedicalExportOrigin] = [
        .automaticTranscription, .modelAuthored(provenance()), .modelAuthored(nil),
    ]

    private func export(_ format: ExportFormat, origin: MedicalExportOrigin) throws -> Data {
        let lease = try service.createExportLease(transcript: Self.transcript, duration: "02:00",
                                                  date: Date(timeIntervalSince1970: 1_700_000_000),
                                                  format: format, origin: origin)
        defer { service.leases.release(lease) }
        return try Data(contentsOf: lease.fileURL)
    }

    // MARK: - The statement

    func testTheStatementSaysWhatTheTextIs() {
        XCTAssertTrue(MedicalExportOrigin.automaticTranscription.statement
            .hasPrefix("Automatic speech-to-text transcription"))
        XCTAssertTrue(MedicalExportOrigin.automaticTranscription.statement.contains("Not AI-generated"))
        XCTAssertTrue(MedicalExportOrigin.modelAuthored(Self.provenance()).statement
            .hasPrefix("AI-generated by test-model-1"))
        XCTAssertEqual(MedicalExportOrigin.modelAuthored(nil).statement,
                       "AI-generated text. The model was not recorded.")
        for origin in Self.origins {
            XCTAssertFalse(origin.statement.contains(Self.promptCanary))
        }
    }

    // MARK: - Every format, both origins

    func testPlainTextLeadsWithTheStatement() throws {
        for origin in Self.origins {
            let text = try XCTUnwrap(String(data: export(.plainText, origin: origin), encoding: .utf8))
            XCTAssertEqual(text.components(separatedBy: "\n").first, origin.statement)
            XCTAssertTrue(text.hasSuffix(Self.transcript))
            XCTAssertFalse(text.contains(Self.promptCanary))
        }
    }

    func testPDFStatesTheOriginInPrintAndInMetadata() throws {
        for origin in Self.origins {
            let data = try export(.pdf, origin: origin)
            let document = try XCTUnwrap(PDFDocument(data: data))
            let attributes = try XCTUnwrap(document.documentAttributes)
            XCTAssertEqual(attributes[PDFDocumentAttribute.titleAttribute] as? String,
                           MedicalExportService.pdfTitle)
            XCTAssertEqual(attributes[PDFDocumentAttribute.subjectAttribute] as? String, origin.statement)
            let xmp = try XCTUnwrap(PDFMetadataProbe.xmp(in: data), "no XMP")
            XCTAssertTrue(PDFMetadataProbe.isWellFormedXML(Data(xmp.utf8)))
            XCTAssertFalse(xmp.contains(Self.clinicalCanary), "clinical text in the metadata")
            XCTAssertFalse(PDFMetadataProbe.contains(data, Self.promptCanary))

            // Printed above the transcript, as well as in the metadata.
            let printed = (document.string ?? "").replacingOccurrences(of: "\n", with: " ")
            XCTAssertTrue(printed.contains(String(origin.statement.prefix(30))), printed)

            switch origin {
            case .automaticTranscription:
                XCTAssertTrue(xmp.contains(PDFProvenanceStampTests.composite))
                XCTAssertFalse(PDFMetadataProbe.keywords(attributes).contains("AI-generated"),
                               "a transcription is not claimed as AI-generated")
            case .modelAuthored(let provenance):
                XCTAssertTrue(xmp.contains("\"\(PDFProvenanceStampTests.trained)\""))
                XCTAssertTrue(PDFMetadataProbe.keywords(attributes).contains("AI-generated"))
                if let provenance { XCTAssertTrue(xmp.contains(provenance.promptVersionDigest)) }
            }
        }
    }

    func testFHIRDocumentCarriesTheTagAndTheSentence() throws {
        for origin in Self.origins {
            let json = try XCTUnwrap(JSONSerialization.jsonObject(with: export(.fhirJson, origin: origin))
                                     as? [String: Any])
            assertTagged(json, origin: origin)
        }
    }

    func testHL7CarriesAnNTEAfterTheObservation() throws {
        for origin in Self.origins {
            let message = try XCTUnwrap(String(data: export(.hl7, origin: origin), encoding: .utf8))
            let segments = message.components(separatedBy: "\n").map { String($0.prefix(4)) }
            XCTAssertEqual(segments, ["MSH|", "EVN|", "TXA|", "OBX|", "NTE|"])
            let nte = try XCTUnwrap(message.components(separatedBy: "\n").last)
            XCTAssertTrue(nte.hasPrefix("NTE|1||"))
            XCTAssertEqual(nte.components(separatedBy: "|").count, 4, "the statement is one field")
            XCTAssertTrue(nte.contains(String(origin.statement.prefix(20))))
            XCTAssertFalse(nte.contains(Self.clinicalCanary))
            XCTAssertFalse(message.contains(Self.promptCanary))
        }
    }

    /// The statement is escaped like the transcript: a `|` in a model identifier cannot open a
    /// new field.
    func testTheNTEStatementIsEscaped() throws {
        let odd = AIProvenance(modelIdentifier: "vendor|model^1", providerClass: .cloud,
                               promptVersionDigest: "abc", appVersion: "1")
        let message = try XCTUnwrap(String(data: export(.hl7, origin: .modelAuthored(odd)), encoding: .utf8))
        let nte = try XCTUnwrap(message.components(separatedBy: "\n").last)
        XCTAssertEqual(nte.components(separatedBy: "|").count, 4)
        XCTAssertTrue(nte.contains("vendor\\F\\model\\S\\1"))
    }

    // MARK: - The network POST

    func testTheFHIRPostCarriesTheTag() throws {
        var config = store.configuration
        config.baseURL = "https://fhir.example.com/r4"
        store.save(config)
        try store.storeCredential(FHIRCredential(bearerToken: "test-token"))
        let context = try store.requestContext()

        for origin in Self.origins {
            let request = try XCTUnwrap(service.fhirSubmissionRequest(
                transcript: Self.transcript, duration: "02:00", date: Date(), origin: origin, context: context))
            XCTAssertEqual(request.httpMethod, "POST")
            let body = try XCTUnwrap(request.httpBody)
            let json = try XCTUnwrap(JSONSerialization.jsonObject(with: body) as? [String: Any])
            assertTagged(json, origin: origin)
        }
    }

    // MARK: - Helper

    private func assertTagged(_ json: [String: Any], origin: MedicalExportOrigin,
                              file: StaticString = #filePath, line: UInt = #line) {
        let tags = (json["meta"] as? [String: Any])?["tag"] as? [[String: String]] ?? []
        XCTAssertEqual(tags, origin.fhirTags, file: file, line: line)
        let originTag = tags.first { $0["system"] == MedicalExportOrigin.fhirTagSystem }
        let modelTag = tags.first { $0["system"] == MedicalExportOrigin.fhirModelTagSystem }
        switch origin {
        case .automaticTranscription:
            XCTAssertEqual(originTag?["code"], "automatic-transcription", file: file, line: line)
            XCTAssertNil(modelTag, file: file, line: line)
        case .modelAuthored(let provenance):
            XCTAssertEqual(originTag?["code"], "ai-generated", file: file, line: line)
            XCTAssertEqual(modelTag?["code"], provenance?.modelIdentifier ?? "unrecorded", file: file, line: line)
        }
        let description = json["description"] as? String ?? ""
        XCTAssertTrue(description.hasSuffix(origin.statement), description, file: file, line: line)
        // The provenance carries no clinical text and no instructions.
        let tagText = tags.flatMap { $0.values }.joined(separator: " ")
        XCTAssertFalse(tagText.contains(Self.clinicalCanary), file: file, line: line)
        XCTAssertFalse(description.contains(Self.clinicalCanary), file: file, line: line)
        XCTAssertFalse(tagText.contains(Self.promptCanary) || description.contains(Self.promptCanary),
                       file: file, line: line)
    }
}
