import XCTest
@testable import OpenGlasses

// Plan HQ P1 item 4 — model text that is saved or shared says who wrote it: saved notes, vault
// entries, the chat transcript share and the agent archive's documents.

// MARK: - Saved and shared text

@MainActor
final class SavedTextMarkerTests: XCTestCase {

    func testSaveNoteRecordsThatTheAssistantWroteIt() async throws {
        let key = "nativeTool_savedNotes"
        let saved = UserDefaults.standard.data(forKey: key)
        defer {
            if let saved { UserDefaults.standard.set(saved, forKey: key) }
            else { UserDefaults.standard.removeObject(forKey: key) }
        }
        UserDefaults.standard.removeObject(forKey: key)

        _ = try await SaveNoteTool().execute(args: ["content": "Buy filters", "title": "Shop"])
        let notes = try JSONDecoder().decode([StoredQuickNote].self,
                                             from: XCTUnwrap(UserDefaults.standard.data(forKey: key)))
        XCTAssertEqual(notes.last?.content, "Buy filters")
        XCTAssertEqual(notes.last?.origin, SavedNoteOrigin.assistant)
    }

    /// Notes saved before the field existed still decode, with no origin.
    func testOlderNotesDecodeWithoutAnOrigin() throws {
        let legacy = #"[{"title":"Old","content":"x","timestamp":700000000}]"#
        let notes = try JSONDecoder().decode([StoredQuickNote].self, from: Data(legacy.utf8))
        XCTAssertEqual(notes.first?.content, "x")
        XCTAssertNil(notes.first?.origin)
    }

    func testVaultEntriesCarryTheMarkerUnderTheHeading() throws {
        let root = FileManager.default.temporaryDirectory
            .appendingPathComponent("NotesVaultMarker-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: root) }
        let manifest = VaultManifest(id: "notes", name: "Notes", version: "1.0.0",
                                     files: ["general.md", "people.md", "ideas.md", "todos.md"],
                                     proceduresDir: nil, gating: .init(iap: nil), promptRules: [],
                                     sourceAttributionFormat: "Source: {files}",
                                     sourceAttributionRequired: false)
        let store = VaultStore(manifest: manifest, bundleRoot: nil, overlayRoot: root)

        let reply = NotesVaultTool().log(args: ["action": "log", "file": "ideas", "entry": "Solar dehumidifier"],
                                         store: store)
        XCTAssertTrue(reply.hasPrefix("Noted in ideas"))
        let text = try XCTUnwrap(store.read("ideas.md"))
        let lines = text.components(separatedBy: "\n")
        XCTAssertTrue(lines[0].hasPrefix("## "), "the existing heading is unchanged")
        XCTAssertEqual(Array(lines.dropFirst()), ["", "Solar dehumidifier", "", "_Written by Avenkin AI from your dictation._"])
        XCTAssertEqual(NotesVaultTool.aiMarker, "_Written by Avenkin AI from your dictation._")
    }

    func testTheChatShareSaysTheAssistantTurnsAreAIGenerated() {
        var thread = ConversationThread(mode: "direct", title: "Boiler")
        thread.messages = [ConversationMessage(role: "user", content: "Hi"),
                           ConversationMessage(role: "assistant", content: "Hello")]
        let lines = ChatThreadView.threadAsText(thread).components(separatedBy: "\n")
        XCTAssertEqual(lines[0], "# Boiler")
        XCTAssertTrue(lines[1].hasPrefix("Date: "))
        XCTAssertEqual(lines[2], "Assistant turns are AI-generated by Avenkin AI")
        XCTAssertEqual(lines[2], String(localized: "Assistant turns are AI-generated by \("Avenkin AI")"))
        XCTAssertEqual(lines[3], "")
        XCTAssertEqual(lines[4], "**You**: Hi")
        XCTAssertFalse(lines[2].contains("Plan"))
    }

    func testArchiveAgentDocumentsOpenWithTheProvenanceComment() {
        XCTAssertEqual(AgentDataExporter.markedAgentDocument("# Soul\nKind."),
                       "<!-- ai-generated: see provenance.json -->\n# Soul\nKind.")
        XCTAssertEqual(AgentDataExporter.markedAgentDocument(""), "<!-- ai-generated: see provenance.json -->\n")
        // The manifest it points at lists the three documents.
        let applies = AgentArchiveProvenance.manifest(nil)["applies_to"] as? [String] ?? []
        for name in ["soul.md", "skills.md", "memory.md"] { XCTAssertTrue(applies.contains(name), name) }
    }
}
