import SwiftUI
import AVFoundation
import CoreLocation
import MWDATCore
import Speech

/// Full-screen onboarding flow — Apple HIG compliant.
///
/// Pages:
///   1. Welcome — what OpenGlasses is, AI transparency disclosure
///   2. Choose Provider — pick an AI provider (large tap targets)
///   3. Access Key — paste key, link to get one, inline validation
///   4. Ready — success, get started
///
/// Design: dark background, system typography, white/monochrome highlights.
/// Follows Apple Generative AI HIG — discloses AI use, sets expectations,
/// communicates that responses may contain errors.
struct OnboardingView: View {
    @Binding var isVisible: Bool
    @EnvironmentObject var appState: AppState

    @State private var page = 0
    @State private var selectedProvider: LLMProvider?
    @State private var apiKey = ""
    @State private var modelName = ""
    @State private var isValidating = false
    @State private var validationError: String?
    @State private var keyValid = false
    @State private var availableModels: [ModelFetcher.RemoteModel] = []
    @State private var selectedModelId: String?

    // Optional service keys
    @State private var elevenLabsKey = ""
    @State private var perplexityKey = ""

    // Permissions state
    @State private var micGranted = false
    @State private var locationGranted = false
    @State private var bluetoothConfigured = false
    @State private var speechGranted = false
    @State private var homeKitGranted = false

    // Connect glasses state (page 5)
    @State private var cameraGranted = false
    @State private var metaRegistered = false
    @State private var registrationStatus = ""
    @State private var isRegistering = false

    private let totalPages = 7

    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()

            VStack(spacing: 0) {
                // Page indicator
                HStack(spacing: 8) {
                    ForEach(0..<totalPages, id: \.self) { i in
                        Capsule()
                            .fill(i == page ? Color.white : Color.white.opacity(0.2))
                            .frame(width: i == page ? 24 : 8, height: 4)
                            .animation(.easeInOut(duration: 0.25), value: page)
                    }
                }
                .padding(.top, 16)
                .padding(.bottom, 24)
                .accessibilityElement()
                .accessibilityLabel("Page \(page + 1) of \(totalPages)")

                // Content — uses conditional views instead of paged TabView
                // so text fields on the API key page respond to taps immediately
                // (paged TabView's swipe gestures steal focus from text fields)
                Group {
                    switch page {
                    case 0: welcomePage
                    case 1: providerPage
                    case 2: apiKeyPage
                    case 3: servicesPage
                    case 4: permissionsPage
                    case 5: connectGlassesPage
                    case 6: readyPage
                    default: EmptyView()
                    }
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
                .animation(.easeInOut(duration: 0.3), value: page)
            }
        }
        .preferredColorScheme(.dark)
    }

    // MARK: - Page 1: Welcome

    private var welcomePage: some View {
        VStack(spacing: 0) {
            Spacer()

            VStack(spacing: 20) {
                LogoIcon(size: 80)
                    .foregroundStyle(.white)

                Text("OpenGlasses")
                    .font(.largeTitle.weight(.bold))
                    .foregroundStyle(.white)

                Text("AI assistant for your smart glasses")
                    .font(.title3)
                    .foregroundStyle(.white.opacity(0.7))
            }

            Spacer()

            // AI transparency disclosure (Apple Generative AI HIG)
            VStack(alignment: .leading, spacing: 12) {
                featureRow(
                    icon: "brain.head.profile",
                    title: "Powered by AI",
                    detail: "Conversations are processed by the AI provider you choose. Responses are generated by AI and may not always be accurate."
                )
                featureRow(
                    icon: "lock.shield",
                    title: "Your keys, your data",
                    detail: "Your access key connects directly to your provider. We never see or store your conversations."
                )
                featureRow(
                    icon: "mic.badge.xmark",
                    title: "Microphone access",
                    detail: "Voice input is processed on-device for wake word detection and sent to your provider for transcription."
                )
            }
            .padding(.horizontal, 28)

            Spacer()

            primaryButton("Get Started") {
                withAnimation { page = 1 }
            }
            skipButton()
        }
        .padding(.bottom, 20)
    }

    // MARK: - Page 2: Choose Provider

    private var providerPage: some View {
        VStack(spacing: 0) {
            VStack(spacing: 8) {
                Text("Choose your AI")
                    .font(.title2.weight(.bold))
                    .foregroundStyle(.white)
                Text("Pick a provider. You can add more later in Settings.")
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.6))
                    .multilineTextAlignment(.center)
            }
            .padding(.top, 8)
            .padding(.horizontal, 28)

            ScrollView {
                VStack(spacing: 12) {
                    providerCard(
                        provider: .anthropic,
                        name: "Anthropic",
                        model: "Claude",
                        detail: "Best for reasoning and conversation",
                        icon: "brain"
                    )
                    providerCard(
                        provider: .gemini,
                        name: "Google",
                        model: "Gemini",
                        detail: "Free tier available, vision capable",
                        icon: "sparkles"
                    )
                    providerCard(
                        provider: .openai,
                        name: "OpenAI",
                        model: "GPT-4o",
                        detail: "Realtime voice mode available",
                        icon: "waveform"
                    )
                    providerCard(
                        provider: .groq,
                        name: "Groq",
                        model: "Llama / Mixtral",
                        detail: "Ultra-fast inference, free tier",
                        icon: "bolt"
                    )
                    providerCard(
                        provider: .qwen,
                        name: "Qwen",
                        model: "Qwen3.5 Plus",
                        detail: "Vision capable, bring your own key",
                        icon: "globe.asia.australia"
                    )
                    providerCard(
                        provider: .zai,
                        name: "Z.ai",
                        model: "GLM-4.5",
                        detail: "Bring your own key",
                        icon: "bolt.circle"
                    )

                    // Collapsed section for other providers
                    DisclosureGroup {
                        VStack(spacing: 12) {
                            providerCard(
                                provider: .openrouter,
                                name: "OpenRouter",
                                model: "500+ models",
                                detail: "Access many providers through one key",
                                icon: "arrow.triangle.branch"
                            )
                        }
                    } label: {
                        Text("More providers")
                            .font(.subheadline.weight(.medium))
                            .foregroundStyle(.white.opacity(0.6))
                    }
                    .tint(.white.opacity(0.4))
                }
                .padding(.horizontal, 20)
                .padding(.top, 20)
                .padding(.bottom, 32)
            }

            if selectedProvider != nil {
                primaryButton("Continue") {
                    configureDefaults()
                    withAnimation { page = 2 }
                }
                .padding(.bottom, 20)
            }
        }
    }

    // MARK: - Page 3: Access Key

    private var apiKeyPage: some View {
        let provider = selectedProvider ?? .anthropic
        let needsKey = provider.requiresAPIKey

        return VStack(spacing: 0) {
            VStack(spacing: 8) {
                Text(needsKey ? "Add your access key" : "You're all set")
                    .font(.title2.weight(.bold))
                    .foregroundStyle(.white)
                if needsKey {
                    Text("Paste your \(provider.displayName) access key below")
                        .font(.subheadline)
                        .foregroundStyle(.white.opacity(0.6))
                }
            }
            .padding(.top, 8)
            .padding(.horizontal, 28)

            Spacer()

            if needsKey {
                VStack(spacing: 16) {
                    // Access Key input
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Access Key")
                            .font(.caption.weight(.medium))
                            .foregroundStyle(.white.opacity(0.5))

                        HStack {
                            SecureField("sk-...", text: $apiKey)
                                .font(.system(.body, design: .monospaced))
                                .autocorrectionDisabled()
                                .textInputAutocapitalization(.never)
                                .foregroundStyle(.white)
                                .onChange(of: apiKey) { _, _ in
                                    validationError = nil
                                    keyValid = false
                                    availableModels = []
                                    selectedModelId = nil
                                }

                            if !apiKey.isEmpty {
                                Button {
                                    apiKey = ""
                                } label: {
                                    Image(systemName: "xmark.circle.fill")
                                        .foregroundStyle(.white.opacity(0.3))
                                }
                            }
                        }
                        .padding(14)
                        .contentShape(Rectangle())
                        .background(Color.white.opacity(0.08), in: RoundedRectangle(cornerRadius: 12))
                        .overlay(
                            RoundedRectangle(cornerRadius: 12)
                                .strokeBorder(
                                    validationError != nil ? Color.red.opacity(0.6) :
                                    keyValid ? Color.green.opacity(0.6) :
                                    Color.white.opacity(0.1),
                                    lineWidth: 1
                                )
                        )

                        if let error = validationError {
                            Text(error)
                                .font(.caption)
                                .foregroundStyle(.red.opacity(0.8))
                        }
                        if keyValid {
                            HStack(spacing: 4) {
                                Image(systemName: "checkmark.circle.fill")
                                    .foregroundStyle(.green)
                                Text(availableModels.isEmpty ? "Key valid" : "Key valid — \(availableModels.count) models available")
                                    .foregroundStyle(.green.opacity(0.8))
                            }
                            .font(.caption)
                        }
                    }
                    .padding(.horizontal, 28)

                    // "Get API Key" deep link
                    if apiKey.isEmpty, let url = provider.consoleURL {
                        Link(destination: url) {
                            HStack(spacing: 6) {
                                Image(systemName: "arrow.up.right.square")
                                Text("Get your API key from \(url.host ?? provider.displayName)")
                            }
                            .font(.subheadline.weight(.medium))
                            .foregroundStyle(.white.opacity(0.7))
                        }
                        .padding(.horizontal, 28)
                    }

                    // Model picker (shown after successful validation)
                    if keyValid && !availableModels.isEmpty {
                        VStack(alignment: .leading, spacing: 8) {
                            Text("Select Model")
                                .font(.caption.weight(.medium))
                                .foregroundStyle(.white.opacity(0.5))

                            ScrollView {
                                VStack(spacing: 6) {
                                    ForEach(availableModels) { model in
                                        Button {
                                            selectedModelId = model.id
                                        } label: {
                                            HStack {
                                                Text(model.name)
                                                    .font(.subheadline)
                                                    .foregroundStyle(.white)
                                                    .lineLimit(1)
                                                Spacer()
                                                if selectedModelId == model.id {
                                                    Image(systemName: "checkmark")
                                                        .font(.caption.weight(.semibold))
                                                        .foregroundStyle(.white)
                                                }
                                            }
                                            .padding(.horizontal, 14)
                                            .padding(.vertical, 10)
                                            .background(
                                                RoundedRectangle(cornerRadius: 10)
                                                    .fill(selectedModelId == model.id
                                                          ? Color.white.opacity(0.1)
                                                          : Color.white.opacity(0.05))
                                            )
                                        }
                                        .buttonStyle(.plain)
                                    }
                                }
                            }
                            .frame(maxHeight: 200)
                        }
                        .padding(.horizontal, 28)
                    }

                    // Link to get a key
                    Button {
                        openAPIKeyURL(for: provider)
                    } label: {
                        HStack(spacing: 6) {
                            Image(systemName: "arrow.up.right.square")
                                .font(.caption)
                            Text(apiKeyURLLabel(for: provider))
                                .font(.subheadline)
                        }
                        .foregroundStyle(.white.opacity(0.7))
                    }
                }
            } else {
                // Subscription providers — no key needed
                VStack(spacing: 16) {
                    Image(systemName: "checkmark.circle")
                        .font(.system(size: 48, weight: .regular))
                        .foregroundStyle(.green)
                    Text("\(provider.displayName) doesn't require an access key.")
                        .font(.subheadline)
                        .foregroundStyle(.white.opacity(0.7))
                        .multilineTextAlignment(.center)
                }
            }

            Spacer()

            if needsKey {
                if keyValid {
                    primaryButton("Continue") {
                        saveModel()
                        withAnimation { page = 3 }
                    }
                } else {
                    primaryButton(isValidating ? "Validating..." : "Validate Key") {
                        validateKey()
                    }
                    .disabled(apiKey.trimmingCharacters(in: .whitespaces).isEmpty || isValidating)
                }

                Button {
                    if !apiKey.trimmingCharacters(in: .whitespaces).isEmpty {
                        saveModel()
                    }
                    withAnimation { page = 3 }
                } label: {
                    Text(keyValid ? "Skip model selection" : "I'll add it later")
                        .font(.subheadline)
                        .foregroundStyle(.white.opacity(0.4))
                }
                .padding(.top, 4)
                .padding(.bottom, 20)
            } else {
                primaryButton("Continue") {
                    saveModel()
                    withAnimation { page = 3 }
                }
                .padding(.bottom, 20)
            }
        }
    }

    // MARK: - Page 4: Services (Optional)

    private var servicesPage: some View {
        VStack(spacing: 0) {
            VStack(spacing: 8) {
                Text("Enhance your experience")
                    .font(.title2.weight(.bold))
                    .foregroundStyle(.white)
                Text("Optional — add these later in Settings if you prefer.")
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.6))
            }
            .padding(.top, 8)
            .padding(.horizontal, 28)

            Spacer()

            VStack(spacing: 20) {
                // ElevenLabs
                VStack(alignment: .leading, spacing: 8) {
                    HStack(spacing: 8) {
                        Image(systemName: "waveform")
                            .foregroundStyle(.white.opacity(0.7))
                            .frame(width: 24)
                        Text("ElevenLabs Voice")
                            .font(.subheadline.weight(.medium))
                            .foregroundStyle(.white)
                    }

                    SecureField("ElevenLabs API Key", text: $elevenLabsKey)
                        .font(.system(.body, design: .monospaced))
                        .autocorrectionDisabled()
                        .textInputAutocapitalization(.never)
                        .foregroundStyle(.white)
                        .padding(14)
                        .contentShape(Rectangle())
                        .background(Color.white.opacity(0.08), in: RoundedRectangle(cornerRadius: 12))
                        .overlay(
                            RoundedRectangle(cornerRadius: 12)
                                .strokeBorder(elevenLabsKey.isEmpty ? Color.white.opacity(0.1) : Color.green.opacity(0.6), lineWidth: 1)
                        )

                    if elevenLabsKey.isEmpty {
                        Link(destination: URL(string: "https://elevenlabs.io/app/settings/api-keys")!) {
                            HStack(spacing: 4) {
                                Image(systemName: "arrow.up.right.square")
                                    .font(.caption)
                                Text("Get key from elevenlabs.io")
                            }
                            .font(.caption)
                            .foregroundStyle(.white.opacity(0.5))
                        }
                    }

                    Text("Natural-sounding voice. Without this, the built-in iOS voice is used.")
                        .font(.caption)
                        .foregroundStyle(.white.opacity(0.35))
                }

                // Perplexity
                VStack(alignment: .leading, spacing: 8) {
                    HStack(spacing: 8) {
                        Image(systemName: "magnifyingglass")
                            .foregroundStyle(.white.opacity(0.7))
                            .frame(width: 24)
                        Text("Perplexity Search")
                            .font(.subheadline.weight(.medium))
                            .foregroundStyle(.white)
                    }

                    SecureField("Perplexity API Key", text: $perplexityKey)
                        .font(.system(.body, design: .monospaced))
                        .autocorrectionDisabled()
                        .textInputAutocapitalization(.never)
                        .foregroundStyle(.white)
                        .padding(14)
                        .contentShape(Rectangle())
                        .background(Color.white.opacity(0.08), in: RoundedRectangle(cornerRadius: 12))
                        .overlay(
                            RoundedRectangle(cornerRadius: 12)
                                .strokeBorder(perplexityKey.isEmpty ? Color.white.opacity(0.1) : Color.green.opacity(0.6), lineWidth: 1)
                        )

                    if perplexityKey.isEmpty {
                        Link(destination: URL(string: "https://www.perplexity.ai/settings/api")!) {
                            HStack(spacing: 4) {
                                Image(systemName: "arrow.up.right.square")
                                    .font(.caption)
                                Text("Get key from perplexity.ai")
                            }
                            .font(.caption)
                            .foregroundStyle(.white.opacity(0.5))
                        }
                    }

                    Text("AI-powered web search with cited sources. Without this, DuckDuckGo is used.")
                        .font(.caption)
                        .foregroundStyle(.white.opacity(0.35))
                }
            }
            .padding(.horizontal, 28)

            // iOS Voice tip
            VStack(alignment: .leading, spacing: 8) {
                HStack(spacing: 8) {
                    Image(systemName: "speaker.wave.2")
                        .foregroundStyle(.white.opacity(0.7))
                        .frame(width: 24)
                    Text("iOS Fallback Voice")
                        .font(.subheadline.weight(.medium))
                        .foregroundStyle(.white)
                }

                if hasPremiumVoiceInstalled {
                    HStack(spacing: 6) {
                        Image(systemName: "checkmark.circle.fill")
                            .foregroundStyle(.green)
                        Text("Premium voice detected")
                            .foregroundStyle(.white.opacity(0.6))
                    }
                    .font(.caption)
                } else {
                    Text("Go to Settings → Accessibility → Spoken Content → Voices to download a premium voice.")
                        .font(.caption)
                        .foregroundStyle(.white.opacity(0.35))
                }
            }
            .padding(.horizontal, 28)

            Spacer()

            primaryButton("Continue") {
                // Save any keys the user entered
                if !elevenLabsKey.isEmpty {
                    Config.setElevenLabsAPIKey(elevenLabsKey)
                }
                if !perplexityKey.isEmpty {
                    Config.setPerplexityAPIKey(perplexityKey)
                }
                withAnimation { page = 4 }
            }
            .padding(.bottom, 4)

            skipButton()
        }
    }

    /// Check if any enhanced/premium quality voice is installed.
    private var hasPremiumVoiceInstalled: Bool {
        AVSpeechSynthesisVoice.speechVoices().contains { voice in
            voice.quality == .enhanced || voice.quality == .premium
        }
    }

    // MARK: - Page 5: Permissions

    private var permissionsPage: some View {
        VStack(spacing: 0) {
            VStack(spacing: 8) {
                Text("Permissions")
                    .font(.title2.weight(.bold))
                    .foregroundStyle(.white)
                Text("OpenGlasses needs a few permissions to work.")
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.6))
            }
            .padding(.top, 8)
            .padding(.horizontal, 28)

            Spacer()

            VStack(spacing: 16) {
                // Microphone
                permissionRow(
                    icon: "mic.fill",
                    title: "Microphone",
                    detail: "For wake word detection and voice commands",
                    granted: micGranted
                ) {
                    await requestMicPermission()
                }

                // Speech Recognition
                permissionRow(
                    icon: "waveform",
                    title: "Speech Recognition",
                    detail: "To understand what you say",
                    granted: speechGranted
                ) {
                    await requestSpeechPermission()
                }

                // Location
                permissionRow(
                    icon: "location.fill",
                    title: "Location",
                    detail: "For weather, nearby places, and context",
                    granted: locationGranted
                ) {
                    requestLocationPermission()
                }

                // Bluetooth / Wearables SDK
                permissionRow(
                    icon: "antenna.radiowaves.left.and.right",
                    title: "Bluetooth",
                    detail: "To connect to your Ray-Ban Meta glasses",
                    granted: bluetoothConfigured
                ) {
                    configureWearablesSDK()
                }

                // HomeKit
                permissionRow(
                    icon: "house.fill",
                    title: "Home Data",
                    detail: "To control lights, locks, and smart home devices",
                    granted: homeKitGranted
                ) {
                    await requestHomeKitPermission()
                }
            }
            .padding(.horizontal, 28)

            Spacer()

            primaryButton("Continue") {
                withAnimation { page = 5 }
            }
            .opacity(micGranted ? 1 : 0.4)
            .disabled(!micGranted)
            .padding(.bottom, 4)

            if !micGranted {
                Text("Microphone permission is required")
                    .font(.caption)
                    .foregroundStyle(.white.opacity(0.35))
                    .padding(.bottom, 8)
            } else {
                skipButton()
            }
        }
        .onAppear { checkExistingPermissions() }
    }

    private func permissionRow(
        icon: String,
        title: String,
        detail: String,
        granted: Bool,
        action: @escaping () async -> Void
    ) -> some View {
        HStack(spacing: 14) {
            Group {
                if icon == "OpenGlassesLogo" {
                    LogoIcon(size: 22)
                } else {
                    Image(systemName: icon)
                        .font(.system(size: 20, weight: .medium))
                }
            }
            .foregroundStyle(granted ? .green : .white.opacity(0.7))
            .frame(width: 32)

            VStack(alignment: .leading, spacing: 2) {
                Text(title)
                    .font(.subheadline.weight(.medium))
                    .foregroundStyle(.white)
                Text(detail)
                    .font(.caption)
                    .foregroundStyle(.white.opacity(0.4))
            }

            Spacer()

            if granted {
                Image(systemName: "checkmark.circle.fill")
                    .font(.title3)
                    .foregroundStyle(.green)
            } else {
                Button {
                    Task { await action() }
                } label: {
                    Text("Grant")
                        .font(.subheadline.weight(.semibold))
                        .foregroundStyle(.black)
                        .padding(.horizontal, 16)
                        .padding(.vertical, 8)
                        .background(.white, in: Capsule())
                }
            }
        }
        .padding(14)
        .background(Color.white.opacity(0.05), in: RoundedRectangle(cornerRadius: 14))
        .overlay(
            RoundedRectangle(cornerRadius: 14)
                .strokeBorder(granted ? Color.green.opacity(0.3) : Color.white.opacity(0.08), lineWidth: 1)
        )
    }

    private func checkExistingPermissions() {
        micGranted = AVCaptureDevice.authorizationStatus(for: .audio) == .authorized
        speechGranted = SFSpeechRecognizer.authorizationStatus() == .authorized
        let locStatus = CLLocationManager().authorizationStatus
        locationGranted = locStatus == .authorizedWhenInUse || locStatus == .authorizedAlways
        bluetoothConfigured = Config.hasCompletedOnboarding
        homeKitGranted = false
        cameraGranted = AVCaptureDevice.authorizationStatus(for: .video) == .authorized
    }

    private func requestMicPermission() async {
        let granted = await AVCaptureDevice.requestAccess(for: .audio)
        micGranted = granted
    }

    private func requestSpeechPermission() async {
        let status = await withCheckedContinuation { cont in
            SFSpeechRecognizer.requestAuthorization { status in
                cont.resume(returning: status)
            }
        }
        speechGranted = status == .authorized
    }

    private func requestLocationPermission() {
        appState.locationService.startTracking()
        // Give time for the dialog to show and user to respond
        Task {
            try? await Task.sleep(nanoseconds: 2_000_000_000)
            let status = CLLocationManager().authorizationStatus
            locationGranted = status == .authorizedWhenInUse || status == .authorizedAlways
        }
    }

    private func configureWearablesSDK() {
        guard !bluetoothConfigured else { return }
        do {
            try Wearables.configure()
            bluetoothConfigured = true
            NSLog("[Onboarding] Wearables SDK configured")
        } catch {
            NSLog("[Onboarding] Wearables.configure() failed: %@", error.localizedDescription)
            // Still mark as configured to avoid retry loop — user can reconnect in Settings
            bluetoothConfigured = true
        }
    }

    private func requestHomeKitPermission() async {
        // HMHomeManager triggers the permission dialog on init.
        // HomeKitTool.prepareShared() creates the singleton manager.
        HomeKitTool.prepareShared()
        // Give time for the permission dialog
        try? await Task.sleep(nanoseconds: 2_000_000_000)
        homeKitGranted = true
    }

    // MARK: - Page 6: Connect Glasses

    private var connectGlassesPage: some View {
        VStack(spacing: 0) {
            VStack(spacing: 8) {
                Text("Connect Your Glasses")
                    .font(.title2.weight(.bold))
                    .foregroundStyle(.white)
                Text("Authorize camera access and link OpenGlasses to the Meta AI app.")
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.6))
                    .multilineTextAlignment(.center)
            }
            .padding(.top, 8)
            .padding(.horizontal, 28)

            Spacer()

            VStack(spacing: 16) {
                // iOS Camera permission
                permissionRow(
                    icon: "camera.fill",
                    title: "Camera",
                    detail: "Required to stream video from your Ray-Ban Meta glasses",
                    granted: cameraGranted
                ) {
                    await requestCameraPermission()
                }

                // Meta AI integration
                VStack(alignment: .leading, spacing: 0) {
                    permissionRow(
                        icon: "OpenGlassesLogo",
                        title: "Meta AI Integration",
                        detail: "Links OpenGlasses to your glasses via the Meta AI app",
                        granted: metaRegistered
                    ) {
                        await connectToMetaAI()
                    }

                    if isRegistering {
                        HStack(spacing: 8) {
                            ProgressView().scaleEffect(0.75)
                            Text(registrationStatus.isEmpty ? "Connecting…" : registrationStatus)
                                .font(.caption)
                                .foregroundStyle(.white.opacity(0.5))
                        }
                        .padding(.horizontal, 14)
                        .padding(.bottom, 8)
                    } else if !registrationStatus.isEmpty && !metaRegistered {
                        Text(registrationStatus)
                            .font(.caption)
                            .foregroundStyle(.orange.opacity(0.9))
                            .padding(.horizontal, 14)
                            .padding(.bottom, 8)
                    }
                }
            }
            .padding(.horizontal, 28)

            Spacer()

            primaryButton("Continue") {
                withAnimation { page = 6 }
            }
            .padding(.bottom, 4)

            Button {
                withAnimation { page = 6 }
            } label: {
                Text("Skip — no glasses yet")
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.4))
            }
            .padding(.top, 4)
            .padding(.bottom, 8)
        }
        .onAppear {
            cameraGranted = AVCaptureDevice.authorizationStatus(for: .video) == .authorized
            metaRegistered = bluetoothConfigured && Wearables.shared.registrationState.rawValue >= 3
        }
    }

    private func requestCameraPermission() async {
        cameraGranted = await AVCaptureDevice.requestAccess(for: .video)
    }

    private func connectToMetaAI() async {
        guard bluetoothConfigured else {
            registrationStatus = "Grant Bluetooth permission first (previous page)"
            return
        }
        isRegistering = true
        registrationStatus = "Registering with Meta AI…"
        await appState.glassesService.connect()
        let state = Wearables.shared.registrationState
        metaRegistered = state.rawValue >= 3
        registrationStatus = metaRegistered
            ? ""
            : "Open the Meta AI app to approve, then tap Connect again"
        isRegistering = false

        // Start observing devices now that registration is in progress
        appState.glassesService.startObserving()
    }

    // MARK: - Page 7: Ready

    private var readyPage: some View {
        VStack(spacing: 0) {
            Spacer()

            VStack(spacing: 20) {
                Image(systemName: "checkmark.circle")
                    .font(.system(size: 56, weight: .regular))
                    .foregroundStyle(.green)

                Text("You're ready")
                    .font(.title.weight(.bold))
                    .foregroundStyle(.white)

                Text("Say \"Hey OpenGlasses\" or tap the mic to start a conversation.")
                    .font(.subheadline)
                    .foregroundStyle(.white.opacity(0.6))
                    .multilineTextAlignment(.center)
                    .padding(.horizontal, 40)
            }

            Spacer()

            // What you can do
            VStack(alignment: .leading, spacing: 14) {
                tipRow(icon: "mic.fill", text: "Voice-first — talk naturally, get spoken answers")
                tipRow(icon: "camera.fill", text: "Show things to the camera for visual AI")
                tipRow(icon: "person.2.fill", text: "Switch personas for different AI personalities")
                tipRow(icon: "gearshape", text: "Add more models or tweak settings anytime")
            }
            .padding(.horizontal, 28)

            Spacer()

            // AI disclosure reminder
            Text("AI responses may contain errors. Verify important information independently.")
                .font(.caption)
                .foregroundStyle(.white.opacity(0.35))
                .multilineTextAlignment(.center)
                .padding(.horizontal, 32)

            primaryButton("Start Using OpenGlasses") {
                completeOnboarding()
            }
            .padding(.top, 12)
            .padding(.bottom, 20)
        }
    }

    // MARK: - Components

    private func featureRow(icon: String, title: String, detail: String) -> some View {
        HStack(alignment: .top, spacing: 14) {
            Image(systemName: icon)
                .font(.system(size: 20, weight: .medium))
                .foregroundStyle(.white.opacity(0.7))
                .frame(width: 32, alignment: .center)
                .padding(.top, 2)

            VStack(alignment: .leading, spacing: 3) {
                Text(title)
                    .font(.subheadline.weight(.semibold))
                    .foregroundStyle(.white)
                Text(detail)
                    .font(.caption)
                    .foregroundStyle(.white.opacity(0.5))
                    .fixedSize(horizontal: false, vertical: true)
            }
        }
    }

    private func tipRow(icon: String, text: String) -> some View {
        HStack(spacing: 12) {
            Image(systemName: icon)
                .font(.system(size: 14, weight: .medium))
                .foregroundStyle(.white.opacity(0.6))
                .frame(width: 24)
            Text(text)
                .font(.subheadline)
                .foregroundStyle(.white.opacity(0.7))
        }
    }

    private func providerCard(
        provider: LLMProvider,
        name: String,
        model: String,
        detail: String,
        icon: String
    ) -> some View {
        let selected = selectedProvider == provider

        return Button {
            withAnimation(.easeInOut(duration: 0.2)) {
                selectedProvider = provider
                modelName = model
            }
        } label: {
            HStack(spacing: 14) {
                Image(systemName: icon)
                    .font(.system(size: 22, weight: .medium))
                    .foregroundStyle(selected ? .white : .white.opacity(0.6))
                    .frame(width: 36)

                VStack(alignment: .leading, spacing: 2) {
                    Text(name)
                        .font(.body.weight(.semibold))
                        .foregroundStyle(.white)
                    Text(detail)
                        .font(.caption)
                        .foregroundStyle(.white.opacity(0.5))
                }

                Spacer()

                if selected {
                    Image(systemName: "checkmark.circle.fill")
                        .font(.title3)
                        .foregroundStyle(.white)
                }
            }
            .padding(16)
            .background(
                RoundedRectangle(cornerRadius: 14)
                    .fill(selected ? Color.white.opacity(0.12) : Color.white.opacity(0.05))
            )
            .overlay(
                RoundedRectangle(cornerRadius: 14)
                    .strokeBorder(
                        selected ? Color.white.opacity(0.3) : Color.white.opacity(0.08),
                        lineWidth: 1
                    )
            )
        }
        .buttonStyle(.plain)
        .accessibilityLabel("\(name) — \(detail)")
    }

    private func primaryButton(_ label: String, action: @escaping () -> Void) -> some View {
        Button(action: action) {
            Text(label)
                .font(.headline)
                .foregroundStyle(.black)
                .frame(maxWidth: 340)
                .padding(.vertical, 16)
                .background(.white, in: RoundedRectangle(cornerRadius: 14))
        }
        .frame(maxWidth: .infinity)
    }

    private func skipButton() -> some View {
        Button {
            completeOnboarding()
        } label: {
            Text("Skip setup")
                .font(.subheadline)
                .foregroundStyle(.white.opacity(0.4))
        }
        .padding(.top, 4)
        .padding(.bottom, 8)
    }

    // MARK: - Logic

    private func configureDefaults() {
        guard let provider = selectedProvider else { return }
        modelName = provider.defaultModel
    }

    private func validateKey() {
        let trimmed = apiKey.trimmingCharacters(in: .whitespaces)
        guard !trimmed.isEmpty else { return }
        guard let provider = selectedProvider else { return }

        // Basic format validation
        if provider == .anthropic && !trimmed.hasPrefix("sk-ant-") {
            validationError = "Anthropic keys start with sk-ant-"
            return
        }
        if provider == .openai && !trimmed.hasPrefix("sk-") {
            validationError = "OpenAI keys start with sk-"
            return
        }

        isValidating = true
        validationError = nil

        Task {
            let models = await ModelFetcher.fetchModels(
                provider: provider,
                apiKey: trimmed,
                baseURL: provider.defaultBaseURL
            )

            await MainActor.run {
                isValidating = false
                if models.isEmpty {
                    // Key may still be valid even if model listing fails — accept it
                    keyValid = true
                    availableModels = []
                    selectedModelId = provider.defaultModel
                } else {
                    keyValid = true
                    availableModels = models
                    // Pre-select the provider's default model if it's in the list
                    if models.contains(where: { $0.id == provider.defaultModel }) {
                        selectedModelId = provider.defaultModel
                    } else {
                        selectedModelId = models.first?.id
                    }
                }
            }
        }
    }

    private func saveModel() {
        guard let provider = selectedProvider else { return }
        let trimmedKey = apiKey.trimmingCharacters(in: .whitespaces)
        let chosenModel = selectedModelId ?? provider.defaultModel

        let model = ModelConfig(
            id: UUID().uuidString,
            name: provider.displayName,
            provider: provider.rawValue,
            apiKey: trimmedKey,
            model: chosenModel,
            baseURL: provider.defaultBaseURL
        )

        var models = Config.savedModels
        // Replace existing model for same provider, or append
        if let idx = models.firstIndex(where: { $0.provider == provider.rawValue }) {
            models[idx] = model
        } else {
            models.append(model)
        }
        Config.setSavedModels(models)
        Config.setActiveModelId(model.id)

        // Update the LLM service so the UI reflects the chosen model immediately
        appState.llmService.refreshActiveModel()

        // Ensure the default persona uses this model (so wake-word doesn't revert to a stale model)
        let personas = Config.savedPersonas
        if personas.count <= 1, let only = personas.first {
            Config.updatePersonaModelId(only.id, modelId: model.id)
        }
    }

    private func completeOnboarding() {
        Config.setHasCompletedOnboarding(true)

        // Ensure Wearables SDK is configured (may already be done from permissions page)
        if !bluetoothConfigured {
            configureWearablesSDK()
        }

        // Start all services that depend on Wearables.shared + permissions
        appState.startPermissionRequiringServices()

        withAnimation(.easeInOut(duration: 0.4)) {
            isVisible = false
        }
    }

    private func openAPIKeyURL(for provider: LLMProvider) {
        let urlString: String
        switch provider {
        case .anthropic: urlString = "https://console.anthropic.com/settings/keys"
        case .openai: urlString = "https://platform.openai.com/api-keys"
        case .gemini: urlString = "https://aistudio.google.com/apikey"
        case .groq: urlString = "https://console.groq.com/keys"
        case .openrouter: urlString = "https://openrouter.ai/keys"
        case .qwen: urlString = "https://dashscope.console.aliyun.com/apiKey"
        case .zai: urlString = "https://open.bigmodel.cn/usercenter/apikeys"
        default: urlString = ""
        }
        if let url = URL(string: urlString) {
            UIApplication.shared.open(url)
        }
    }

    private func apiKeyURLLabel(for provider: LLMProvider) -> String {
        switch provider {
        case .anthropic: return "Get a key at console.anthropic.com"
        case .openai: return "Get a key at platform.openai.com"
        case .gemini: return "Get a key at aistudio.google.com"
        case .groq: return "Get a key at console.groq.com"
        case .openrouter: return "Get a key at openrouter.ai"
        case .qwen: return "Get a key at dashscope.console.aliyun.com"
        case .zai: return "Get a key at open.bigmodel.cn"
        default: return "Get an access key"
        }
    }
}