#!/usr/bin/env bash
#
# Privacy-logging scanner — REPORT ONLY (always exits 0).
#
# Counts what production sources still log directly, and flags the two shapes that most often
# turn a diagnostic line into a data leak: a log call interpolating a variable named after user
# content or a credential, and a log call reading `localizedDescription`.
#
# It is deliberately blunt: it matches text, not syntax, so it over-reports (a comment mentioning
# NSLog counts) and under-reports (a wrapper that hides the call). That is the right trade while
# it is a report — the number is a ledger, not a verdict. Syntax analysis is the P2 job, at which
# point this becomes a gate. Until then it prints a summary CI can parse and watch trend down.
#
# Usage:
#   Scripts/check-privacy-logging.sh            # full report
#   Scripts/check-privacy-logging.sh --ledger   # per-file counts only (the checked-in baseline)
#
# Allowlist: Scripts/privacy-logging-allowlist.txt — one path per line, '#' comments. Allowlisted
# files are counted and reported separately, never silently dropped, so growing the allowlist
# shows up as a reviewable diff rather than a quietly shrinking number.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCES="$REPO_ROOT/OpenGlasses/Sources"
ALLOWLIST="$REPO_ROOT/Scripts/privacy-logging-allowlist.txt"

LEDGER_ONLY=0
[ "${1:-}" = "--ledger" ] && LEDGER_ONLY=1

if [ ! -d "$SOURCES" ]; then
  echo "check-privacy-logging: no sources at $SOURCES — nothing to scan."
  exit 0
fi

# A direct logging call: NSLog(...) or a bare print(...) (not `.print(`, not `sprint(`).
DIRECT_RE='(^|[^A-Za-z0-9_.])(NSLog|print)\('
# Identifiers whose names say the value is user content or a credential. Matched as whole words
# anywhere on a logging line — blunt on purpose; a false positive costs a glance.
RISKY_RE='(args|arguments|result|results|transcript|payload|prompt|url|urlString|absoluteString|token|apiKey|key|secret|cookie|entityId|responseBody|rawText)'

is_allowlisted() {
  [ -f "$ALLOWLIST" ] || return 1
  grep -qxF "$1" <(grep -v '^[[:space:]]*#' "$ALLOWLIST" | grep -v '^[[:space:]]*$')
}

# --- per-file direct-logging counts -------------------------------------------------------------

tmp_counts="$(mktemp)"
trap 'rm -f "$tmp_counts"' EXIT

while IFS= read -r file; do
  rel="${file#"$REPO_ROOT"/}"
  count=$(grep -Ec "$DIRECT_RE" "$file" || true)
  [ "$count" -gt 0 ] && printf '%6d  %s\n' "$count" "$rel" >> "$tmp_counts"
done < <(find "$SOURCES" -name '*.swift' -type f | sort)

total_sites=$(awk '{ s += $1 } END { print s + 0 }' "$tmp_counts")
total_files=$(wc -l < "$tmp_counts" | tr -d ' ')

if [ "$LEDGER_ONLY" -eq 1 ]; then
  echo "# Privacy-logging ledger baseline — direct NSLog/print sites under OpenGlasses/Sources"
  echo "# Generated by Scripts/check-privacy-logging.sh --ledger"
  echo "# sites  file"
  sort -rn "$tmp_counts"
  echo
  echo "# TOTAL ${total_sites} sites across ${total_files} files"
  exit 0
fi

echo "=============================================================================="
echo " Privacy logging report (report-only — this script never fails a build yet)"
echo "=============================================================================="
echo
echo "-- Direct NSLog/print sites, worst files first --------------------------------"
sort -rn "$tmp_counts" | head -25
echo "   ... $total_files files in total (use --ledger for the full table)"
echo

# --- content-shaped interpolation ---------------------------------------------------------------

echo "-- Log calls interpolating content/credential-named identifiers ---------------"
risky_hits=$(grep -REn "$DIRECT_RE" --include='*.swift' "$SOURCES" \
  | grep -Eiw "$RISKY_RE" \
  | sed "s|^$REPO_ROOT/||" || true)
risky_count=$(printf '%s' "$risky_hits" | grep -c . || true)
printf '%s\n' "$risky_hits" | head -40
echo "   ($risky_count flagged)"
echo

# --- localizedDescription -----------------------------------------------------------------------

echo "-- Log calls reading localizedDescription -------------------------------------"
desc_hits=$(grep -REn "$DIRECT_RE" --include='*.swift' "$SOURCES" \
  | grep -F 'localizedDescription' \
  | sed "s|^$REPO_ROOT/||" || true)
desc_count=$(printf '%s' "$desc_hits" | grep -c . || true)
printf '%s\n' "$desc_hits" | head -40
echo "   ($desc_count flagged)"
echo

# --- allowlist ------------------------------------------------------------------------------------

allowlisted_files=0
allowlisted_sites=0
if [ -f "$ALLOWLIST" ]; then
  while IFS= read -r count rel; do
    if is_allowlisted "$rel"; then
      allowlisted_files=$((allowlisted_files + 1))
      allowlisted_sites=$((allowlisted_sites + count))
    fi
  done < <(awk '{ print $1, $2 }' "$tmp_counts")
fi

echo "-- Summary --------------------------------------------------------------------"
echo "PRIVACY_LOG_DIRECT_SITES=$total_sites"
echo "PRIVACY_LOG_DIRECT_FILES=$total_files"
echo "PRIVACY_LOG_RISKY_INTERPOLATIONS=$risky_count"
echo "PRIVACY_LOG_LOCALIZED_DESCRIPTION=$desc_count"
echo "PRIVACY_LOG_ALLOWLISTED_FILES=$allowlisted_files"
echo "PRIVACY_LOG_ALLOWLISTED_SITES=$allowlisted_sites"
echo
echo "Report only — exiting 0. The gate lands with P2, once the ledger is near zero."
exit 0
